package com.medicamentos.model;
// Generated 31/10/2017 08:33:58 PM by Hibernate Tools 5.2.5.Final

import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Establecimiento generated by hbm2java
 */

@Entity
@Table(name = "establecimiento", catalog = "medicamentos")
@SuppressWarnings("serial")
public class Establecimiento implements java.io.Serializable {

	private int id;
	private Usuario usuario;
	private String nit;
	private String nombre;
	private String direccion;
	private String telefono;
	private String ciudad;
	private String email;
	private List<EstablecimientoMedicamento> establecimientoMedicamentos;

	public Establecimiento() {
	}
	
	public Establecimiento(int id) {
		this.id = id;
	}

	public Establecimiento(int id, String nit, String nombre, String direccion, String telefono, String ciudad,
			String email) {
		this.id = id;
		this.nit = nit;
		this.nombre = nombre;
		this.direccion = direccion;
		this.telefono = telefono;
		this.ciudad = ciudad;
		this.email = email;
	}

	public Establecimiento(int id, Usuario usuario, String nit, String nombre, String direccion, String telefono,
			String ciudad, String email, List<EstablecimientoMedicamento> establecimientoMedicamentos) {
		this.id = id;
		this.usuario = usuario;
		this.nit = nit;
		this.nombre = nombre;
		this.direccion = direccion;
		this.telefono = telefono;
		this.ciudad = ciudad;
		this.email = email;
		this.establecimientoMedicamentos = establecimientoMedicamentos;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuario_id")
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Column(name = "nit", unique = true, nullable = false, length = 45)
	public String getNit() {
		return this.nit;
	}

	public void setNit(String nit) {
		this.nit = nit;
	}

	@Column(name = "nombre", nullable = false, length = 95)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "direccion", nullable = false, length = 95)
	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	@Column(name = "telefono", nullable = false, length = 45)
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	@Column(name = "ciudad", nullable = false, length = 45)
	public String getCiudad() {
		return this.ciudad;
	}

	public void setCiudad(String ciudad) {
		this.ciudad = ciudad;
	}

	@Column(name = "email", nullable = false, length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "establecimiento")
	public List<EstablecimientoMedicamento> getEstablecimientoMedicamentos() {
		return this.establecimientoMedicamentos;
	}

	public void setEstablecimientoMedicamentos(List<EstablecimientoMedicamento> establecimientoMedicamentos) {
		this.establecimientoMedicamentos = establecimientoMedicamentos;
	}

}
