package com.medicamentos.model;
// Generated 31/10/2017 08:33:58 PM by Hibernate Tools 5.2.5.Final

import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EstablecimientoMedicamento generated by hbm2java
 */

@Entity
@Table(name = "establecimiento_medicamento", catalog = "medicamentos")
@SuppressWarnings("serial")
public class EstablecimientoMedicamento implements java.io.Serializable {

	private int id;
	private Establecimiento establecimiento;
	private Medicamentos medicamentos;
	private List<Historial> historials;

	public EstablecimientoMedicamento() {
	}
	
	public EstablecimientoMedicamento(int id) {
		this.id = id;
	}

	public EstablecimientoMedicamento(int id, Establecimiento establecimiento, Medicamentos medicamentos) {
		this.id = id;
		this.establecimiento = establecimiento;
		this.medicamentos = medicamentos;
	}

	public EstablecimientoMedicamento(int id, Establecimiento establecimiento, Medicamentos medicamentos,
			List<Historial> historials) {
		this.id = id;
		this.establecimiento = establecimiento;
		this.medicamentos = medicamentos;
		this.historials = historials;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idestablecimiento", nullable = false)
	public Establecimiento getEstablecimiento() {
		return this.establecimiento;
	}

	public void setEstablecimiento(Establecimiento establecimiento) {
		this.establecimiento = establecimiento;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idmedicamento", nullable = false)
	public Medicamentos getMedicamentos() {
		return this.medicamentos;
	}

	public void setMedicamentos(Medicamentos medicamentos) {
		this.medicamentos = medicamentos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "establecimientoMedicamento")
	public List<Historial> getHistorials() {
		return this.historials;
	}

	public void setHistorials(List<Historial> historials) {
		this.historials = historials;
	}

}
