package com.medicamentos.model;
// Generated 31/10/2017 08:33:58 PM by Hibernate Tools 5.2.5.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonFormat;

/**
 * Historial generated by hbm2java
 */

@Entity
@Table(name = "historial", catalog = "medicamentos")
@SuppressWarnings("serial")
public class Historial implements java.io.Serializable {

	private int id;
	private EstablecimientoMedicamento establecimientoMedicamento;
	private int ingreso;
	private String labFarma;
	private int salida;
	private int radFormulas;
	private int saldo;
	private Date fecha;
	private String responsable;

	public Historial() {
	}
	
	public Historial(int id) {
		this.id = id;
	}
	
	public Historial(int id, int ingreso, String labFarma, int salida, int radFormulas) {
		this.id = id;
		this.ingreso = ingreso;
		this.labFarma = labFarma;
		this.salida = salida;
		this.radFormulas = radFormulas;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idestablecimiento_medicamento", nullable = false)
	public EstablecimientoMedicamento getEstablecimientoMedicamento() {
		return this.establecimientoMedicamento;
	}

	public void setEstablecimientoMedicamento(EstablecimientoMedicamento establecimientoMedicamento) {
		this.establecimientoMedicamento = establecimientoMedicamento;
	}

	@Column(name = "ingreso", nullable = false)
	public int getIngreso() {
		return this.ingreso;
	}

	public void setIngreso(int ingreso) {
		this.ingreso = ingreso;
	}

	@Column(name = "lab_farma", nullable = false, length = 95)
	public String getLabFarma() {
		return this.labFarma;
	}

	public void setLabFarma(String labFarma) {
		this.labFarma = labFarma;
	}

	@Column(name = "salida", nullable = false)
	public int getSalida() {
		return this.salida;
	}

	public void setSalida(int salida) {
		this.salida = salida;
	}

	@Column(name = "rad_formulas", nullable = false)
	public int getRadFormulas() {
		return this.radFormulas;
	}

	public void setRadFormulas(int radFormulas) {
		this.radFormulas = radFormulas;
	}

	@Column(name = "saldo", nullable = false, length = 45)
	public int getSaldo() {
		return this.saldo;
	}

	public void setSaldo(int saldo) {
		this.saldo = saldo;
	}

	@Column(name = "fecha", nullable = false, length = 45)
	@Temporal(TemporalType.DATE)
	@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy/MM/dd", timezone="America/Bogota")
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "responsable", nullable = false, length = 45)
	public String getResponsable() {
		return this.responsable;
	}

	public void setResponsable(String responsable) {
		this.responsable = responsable;
	}

}
