package com.medicamentos.model;
// Generated 31/10/2017 08:33:58 PM by Hibernate Tools 5.2.5.Final

import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Medicamentos generated by hbm2java
 */
@Entity
@Table(name = "medicamentos", catalog = "medicamentos")
@SuppressWarnings("serial")
public class Medicamentos implements java.io.Serializable {

	private int id;
	private String nombreGenerico;
	private String nombreComercial;
	private String unidadFarmaceutica;
	private List<EstablecimientoMedicamento> establecimientoMedicamentos;

	public Medicamentos() {
	}

	public Medicamentos(int id, String nombreGenerico) {
		this.id = id;
		this.nombreGenerico = nombreGenerico;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "nombre_generico", nullable = false, length = 45)
	public String getNombreGenerico() {
		return this.nombreGenerico;
	}

	public void setNombreGenerico(String nombreGenerico) {
		this.nombreGenerico = nombreGenerico;
	}

	@Column(name = "nombre_comercial", nullable = false, length = 45)
	public String getNombreComercial() {
		return this.nombreComercial;
	}

	public void setNombreComercial(String nombreComercial) {
		this.nombreComercial = nombreComercial;
	}

	@Column(name = "unidad_farmaceutica", nullable = false, length = 45)
	public String getUnidadFarmaceutica() {
		return this.unidadFarmaceutica;
	}

	public void setUnidadFarmaceutica(String unidadFarmaceutica) {
		this.unidadFarmaceutica = unidadFarmaceutica;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "medicamentos")
	public List<EstablecimientoMedicamento> getEstablecimientoMedicamentos() {
		return this.establecimientoMedicamentos;
	}

	public void setEstablecimientoMedicamentos(List<EstablecimientoMedicamento> establecimientoMedicamentos) {
		this.establecimientoMedicamentos = establecimientoMedicamentos;
	}

}
