package com.medicamentos.model;
// Generated 31/10/2017 08:33:58 PM by Hibernate Tools 5.2.5.Final

import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "usuario", catalog = "medicamentos")
@SuppressWarnings("serial")
public class Usuario implements java.io.Serializable {

	private int id;
	private String identificacion;
	private String clave;
	private String role;
	private char estado;
	private String nombre;
	private List<Establecimiento> establecimientos;

	public Usuario() {
	}

	public Usuario(int id, String identificacion, String clave, String role, char estado) {
		this.id = id;
		this.identificacion = identificacion;
		this.clave = clave;
		this.role = role;
		this.estado = estado;
	}

	public Usuario(int id, String identificacion, String clave, String role, char estado, List<Establecimiento> establecimientos) {
		this.id = id;
		this.identificacion = identificacion;
		this.clave = clave;
		this.role = role;
		this.estado = estado;
		this.establecimientos = establecimientos;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "identificacion", unique = true, nullable = false, length = 45)
	public String getIdentificacion() {
		return this.identificacion;
	}

	public void setIdentificacion(String identificacion) {
		this.identificacion = identificacion;
	}

	@Column(name = "clave", nullable = false, length = 100)
	public String getClave() {
		return this.clave;
	}

	public void setClave(String clave) {
		this.clave = clave;
	}

	@Column(name = "rol", nullable = false, length = 45)
	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public List<Establecimiento> getEstablecimientos() {
		return this.establecimientos;
	}

	public void setEstablecimientos(List<Establecimiento> establecimientos) {
		this.establecimientos = establecimientos;
	}

	@Column(name = "estado", nullable = false, length = 1)
	public char getEstado() {
		return estado;
	}

	public void setEstado(char estado) {
		this.estado = estado;
	}

	@Column(name = "nombre", nullable = false, length = 100)
	public String getNombre() {
		return nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}
	
	

}
